# 1. Tensores

## 1.1. O que são tensores? 
Tensores são um tipo de estrutura de dados muito similares a arrays e matrizes. Em PyTorch, nós usamos tensores para codificar os inputs e outputs do modelo, assim como os parâmetros dele.

Esses tensores são análogos aos arrays em Numpy. Se temos um array 3x3, esse seria um tensor 3x3 no PyTorch. Vamos ver alguns exemplos:

In [1]:
import numpy as np 
import torch

In [2]:
array = [[1, 2, 3], [4, 5, 6], [7, 8, 9]]
np_array = np.array(array)

print(f'Type: {type(np_array)}')
print(f'Shape: {np.shape(np_array)}')
print(np_array)

Type: <class 'numpy.ndarray'>
Shape: (3, 3)
[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [3]:
torch_tensor = torch.tensor(array)
torch_from_numpy = torch.from_numpy(np_array)

print(f'Type: {type(torch_tensor)}')
print(f'Shape: {torch_tensor.shape}')
print(torch_tensor)

Type: <class 'torch.Tensor'>
Shape: torch.Size([3, 3])
tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])


Também temos outras funções parecidas muito comuns nas duas bibliotecas: 

```
- np.ones() = torch.ones()
- np.random.rand() = torch.rand()
- np.zeros() = torch.zeros()
```

In [4]:
print(f"Numpy:\n {np.ones((2,3))}\n")

print(torch.ones((2,3)))

Numpy:
 [[1. 1. 1.]
 [1. 1. 1.]]

tensor([[1., 1., 1.],
        [1., 1., 1.]])


In [5]:
print(f"Numpy:\n {np.zeros((2,3))}\n")

print(torch.zeros(2,3))

Numpy:
 [[0. 0. 0.]
 [0. 0. 0.]]

tensor([[0., 0., 0.],
        [0., 0., 0.]])


In [6]:
print(f"Numpy:\n {np.random.rand(2,3)}\n")

print(torch.rand(2,3))

Numpy:
 [[0.90033934 0.99719812 0.75953743]
 [0.24964706 0.96557391 0.07880709]]

tensor([[0.1448, 0.8870, 0.1457],
        [0.9243, 0.4263, 0.1177]])


## 1.2. Operações com tensores

In [9]:
# We move our tensor to the GPU if available
if torch.cuda.is_available():
    tensor = tensor.to('cuda')

In [8]:
# Indexing & slicing
tensor = torch.ones(4, 4)
tensor[:,1] = 0
print(tensor)

tensor([[1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.]])


In [10]:
# Multiplicação

# element-wise product
print(f"tensor.mul(tensor) \n {tensor.mul(tensor)} \n")

print(f"tensor * tensor \n {tensor * tensor}")

tensor.mul(tensor) 
 tensor([[1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.]], device='cuda:0') 

tensor * tensor 
 tensor([[1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.]], device='cuda:0')


In [11]:
# Multiplicação de matrizes
print(f"tensor.matmul(tensor.T) \n {tensor.matmul(tensor.T)} \n")

print(f"tensor @ tensor.T \n {tensor @ tensor.T}")

tensor.matmul(tensor.T) 
 tensor([[3., 3., 3., 3.],
        [3., 3., 3., 3.],
        [3., 3., 3., 3.],
        [3., 3., 3., 3.]], device='cuda:0') 

tensor @ tensor.T 
 tensor([[3., 3., 3., 3.],
        [3., 3., 3., 3.],
        [3., 3., 3., 3.],
        [3., 3., 3., 3.]], device='cuda:0')


# 2. Redes Neurais - `torch.nn`

Redes Neurais são uma coleção de funções aninhadas que são executadas em algum tipo de dado recebido como input. Definimos essas funções usando parâmetros (com *pesos* e *bias*), que em Pytorch guardamos em tensores. 

Essencialmente, treinar uma rede neural consiste nos seguintes passos:
1. Definir uma rede neural que possui parâmetros treináveis (*pesos*)
2. Iterar sobre um dataset de inputs
3. Processar o input pela rede
4. Computar a loss (quão longe o output está do correto)
5. Propagar gradientes de volta para os parâmetros da rede
6. Atualizar os pesos da rede, geralmente utilizando: 
    `weight = weight - learning_rate * gradient`

Em PyTorch, podemos construir redes neurais utilizando o pacote `torch.nn`.



## Referências
- [Workshop de Redes Neurais - Grupo Turing](https://github.com/GrupoTuring/Workshop-de-redes-neurais)
- [Aula Interna de PyTorch - Grupo Turing](https://drive.google.com/file/d/1UPYbrxl6iZFyCNwoVcxVoMReLU5KX6kE/view)
- [DEEP LEARNING WITH PYTORCH: A 60 MINUTE BLITZ](https://pytorch.org/tutorials/beginner/deep_learning_60min_blitz.html)